version: '3'

services:

    tlsserver:
        container_name: grpctlsserver 
        image: grpcpingpong
        command: server --msg "response from tls server" --port 8090
        network_mode: host
        volumes:
            - /etc/hosts:/etc/hosts

    tlsclient:
        container_name: grpctlsclient 
        image: grpcpingpong
        entrypoint: ""
        command: tail -f /dev/null
        network_mode: host
        volumes:
            - /etc/hosts:/etc/hosts
